@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jul 28 19:58:30 +0200 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim grayscale_filter_behav -key {Behavioral:sim_1:Functional:grayscale_filter} -tclbatch grayscale_filter.tcl -protoinst "protoinst_files/bd_22c4.protoinst" -protoinst "protoinst_files/axi_block_design.protoinst" -view E:/dvs_project_u16/dvs_bypass_pack/grayscale_filter_behav.wcfg -log simulate.log"
call xsim  grayscale_filter_behav -key {Behavioral:sim_1:Functional:grayscale_filter} -tclbatch grayscale_filter.tcl -protoinst "protoinst_files/bd_22c4.protoinst" -protoinst "protoinst_files/axi_block_design.protoinst" -view E:/dvs_project_u16/dvs_bypass_pack/grayscale_filter_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
